- name: "Install tar"
  apt:
    name: tar
    state: present

- name: "Extract artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

# - name: extract artifact
#   become: true
#   unarchive:
#     src: files/artifact.tar.gz 
#     dest: .

# - name: "Extract Artifact"
#   shell: tar xvzf ~/project/artifact.tar.gz

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present

- name: "npm version"
  shell: npm -version

- name: "pm2 stop"
  shell: pm2 stop default

- name: "start server"
  shell: pm2 start npm -- start