- name: "Install tar"
  apt:
    name: tar
    state: present

- name: "create ~/app"
  ansible.builtin.file:
    path: ~/app
    state: directory
    mode: '0755'

- name: "copy files"
  copy:
    src: "~/project/artifact.tar.gz"
    dest: ~/app
    backup: true

- name: "Extract Artifact"
  shell: tar xvzf ~/project/artifact.tar.gz

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present

- name: "npm version"
  shell: npm -version

- name: "pm2 stop"
  shell: pm2 stop default

- name: "start server"
  shell: pm2 start npm -- start