version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
            name: Enter front-end directory
            command: |
              cd cdond-c3-projectstarter/frontend

      - run:
            name: Npm Install
            command: |
              pwd

      - run:
            name: Build Npm
            command: |
              npm run build

      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Enter front-end directory
          command: |
            cd backend
      - run:
          name: Backend install Npm
          command: |
            npm install
      - run:
            name: Backend build Npm
            command: |
              npm run build

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build



workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      