version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/cdond-c3-projectstarter/frontend
    steps:
      - checkout
      - run:
          name: Enter front-end directory
          command: |
            cd frontend
            npm install
            npm run build

      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Enter front-end directory
          command: |
            cd backend
            npm install
            npm run build

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build



workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      