version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Enter front-end directory
          command: |
            cd frontend
      - run:
            name: Npm Init
            command: |
              npm init -y
      - run:
          name: install Npm
          command: |
            npm install

      - run:
            name: Build Npm
            command: |
              npm run build

      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Enter front-end directory
          command: |
            cd backend
      - run:
          name: Backend install Npm
          command: |
            npm install
      - run:
            name: Backend build Npm
            command: |
              npm run build

      - save_cache:
          paths: [backend/node_modules]
          key: backend-build



workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      