# Workflow to ensure whenever a Github PR is submitted, 
# a JIRA ticket gets created automatically. 
name: CI/CD Workflow

# Controls when the action will run. 
on:
  pull_request:
  push:
  # Triggers the workflow on pull request events but only for the master branch
  # pull_request_target:
  #   types: [opened, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install and run frontend build
      run: |
        cd frontend
        npm install
        npm run build
    - name: Install and run backend build
      run: |
        cd backend
        npm install
        npm run build

    # steps:
    # - name: Checkout
    #   uses: actions/checkout@master

    # - name: Login
    #   uses: atlassian/gajira-login@master
    #   env:
    #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
    #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
    # - name: Create NEW JIRA ticket
    #   id: create
    #   uses: atlassian/gajira-create@master
    #   with:
    #     project: CONUPDATE
    #     issuetype: Task
    #     summary: |
    #       Github PR nd9991 - Cloud DevOps Engineer | Repo: ${{ github.repository }}  | PR# ${{github.event.number}}
    #     description: |
    #        Repo link: https://github.com/${{ github.repository }}   
    #        PR no. ${{ github.event.pull_request.number }} 
    #        PR title: ${{ github.event.pull_request.title }}  
    #        PR description: ${{ github.event.pull_request.description }}  
    #        In addition, please resolve other issues, if any. 
    #     fields: '{"components": [{"name":"nd9991 - Cloud DevOps Engineer"}], "customfield_16449":"https://classroom.udacity.com/", "customfield_16450":"Resolve the PR", "labels": ["github"], "priority":{"id": "4"}}'

    # - name: Log created issue
    #   run: echo "Issue ${{ steps.create.outputs.issue }} was created"
